
export const CHANGE_DIR = 'CHANGE_DIR';
export const CHANGE_DIR_DONE = 'CHANGE_DIR_DONE';
export const OPEN_COVER = 'OPEN_COVER';

export const CHANGE_COVER_NAME_FILTER = 'CHANGE_COVER_NAME_FILTER';
export const CHANGE_TAG_FILTER = 'CHANGE_TAG_FILTER';
export const ADD_COVER_FILTER_TAG = 'ADD_COVER_FILTER_TAG';
export const DELETE_COVER_FILTER_TAG = 'DELETE_COVER_FILTER_TAG';
export const TOGGLE_COVER_FILTER_TAG = 'TOGGLE_COVER_FILTER_TAG';
