
export const CHANGE_DIR = 'CHANGE_DIR';
export const OPEN_COVER = 'OPEN_COVER';

export const CHANGE_COVER_NAME_FILTER = 'CHANGE_COVER_NAME_FILTER';
export const ADD_COVER_FILTER_TAG = 'ADD_COVER_FILTER_TAG';
export const REMOVE_COVER_FILTER_TAG = 'REMOVE_COVER_FILTER_TAG';
